from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch

project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.language.model_bundle import load_model_bundle
from src.language.protocol import (
    ProtocolError,
    build_chat_prompt,
    extract_assistant_response,
    generation_stop_ids,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bundle", default="data/models/trading_language/15m")
    parser.add_argument("--temperature", type=float, default=0.45)
    parser.add_argument("--top-k", type=int, default=24)
    parser.add_argument("--top-p", type=float, default=0.88)
    parser.add_argument("--max-new-tokens", type=int, default=180)
    args = parser.parse_args()

    model, tokenizer, manifest = load_model_bundle(args.bundle, device="cpu")
    print(
        f"Loaded {manifest.architecture} "
        f"{manifest.parameter_count / 1e6:.2f}M "
        f"stage={manifest.training_stage} "
        f"context={model.max_seq_len}"
    )

    turns: list[tuple[str, str]] = []
    stop_ids = generation_stop_ids(tokenizer)

    while True:
        try:
            user_input = input("\nYou: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not user_input:
            continue
        if user_input in {"/quit", "/exit"}:
            break
        if user_input == "/reset":
            turns.clear()
            print("Conversation reset.")
            continue

        candidate_turns = turns + [("user", user_input)]
        try:
            prompt = build_chat_prompt(candidate_turns)
        except ProtocolError as exc:
            print(f"Input rejected by language protocol: {exc}")
            continue

        ids = tokenizer.encode(prompt, add_bos=True, add_eos=False)
        if len(ids) > model.max_seq_len:
            # Drop complete oldest turns until the canonical prompt fits. Never
            # slice through the middle of a structural token sequence.
            trimmed = list(candidate_turns)
            while len(trimmed) > 1:
                trimmed = trimmed[1:]
                if trimmed and trimmed[0][0] == "assistant":
                    trimmed = trimmed[1:]
                prompt = build_chat_prompt(trimmed)
                ids = tokenizer.encode(prompt, add_bos=True, add_eos=False)
                if len(ids) <= model.max_seq_len:
                    candidate_turns = trimmed
                    break
            if len(ids) > model.max_seq_len:
                print("Input is longer than the model's trained context window.")
                continue

        output = model.generate(
            torch.tensor([ids], dtype=torch.long),
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
            top_k=args.top_k,
            top_p=args.top_p,
            stop_ids=stop_ids,
        )
        # Generated byte IDs are not guaranteed to form valid UTF-8 while a
        # small model is immature. Preserve the session and surface replacement
        # characters rather than crashing. Corpus/checkpoint decode stays strict.
        decoded = tokenizer.decode(
            output[0].tolist(),
            skip_special=False,
            errors="replace",
        )
        try:
            response = extract_assistant_response(decoded)
        except ProtocolError as exc:
            print(f"Generation violated language protocol: {exc}")
            continue

        print(f"\nVista: {response}")
        turns = candidate_turns + [("assistant", response)]
        turns = turns[-6:]


if __name__ == "__main__":
    main()
